### ISSUE TITLE
Improve Dh_max (maximum hail size diagnotic) plus new WRF/CM1 wrapper

### ISSUE THREAD

**Issue by jason-milbrandt** [jason-milbrandt/P3-microphysics#12]
- optimize 'maxHailSize' function
- relocate call to 'maxHailSize' to hydrometeor type diagnostics
  + add ktop_typeDiag_rain and ktop_typeDiag_ice to optimize calculations

- double-check GEM wrapper (for diag_dhmax)

- add diag_dhmax and surface running mean dhmax fields to CM1

**Comment by jason-milbrandt** [comment]
Melissa:  Let's create separate sub-branches (each of us) off of dev-dhmax for the last two sub-topics.  You do 'dev-dhmax-GEM'; I will do 'dev-dhmax-CM1'.

Points 2 and 2b (relocation of 'maxHailSize' to type diagnostics and stop_typeDiag optimization) are complete.  Point 1 (optimize 'maxHailSize' function) can be addressed later.

**Comment by hmorrison100** [comment]
Jason to merge dev-dhmax to master soon. Hugh to check WRF/CM1 wrapper after that.

**Comment by jason-milbrandt** [comment]
I merged 'master' (v5.2.4) [dmi code + G(mu) calculation] to dev-dhmax.

What is needed to merge dev-dhmax to master is for the code to be tested in GEM.

**Comment by jason-milbrandt** [comment]
'dev-dhmax' branch, which includes changes to wrapper_cm1/wrf, has been merge back to 'master' --> v5.3.0
