### ISSUE TITLE
Correction for using mu_r=0. in lookup table 1 (for both 2MOM and 3MOM)

### ISSUE THREAD

**Issue by MelissaCholette** [jason-milbrandt/P3-microphysics#14]

**Comment by MelissaCholette** [comment]
Here some figures that document the changes in 48-h accumulation fields.
[Mur_LT1-bugfix.pptx](https://github.com/jason-milbrandt/P3-microphysics/files/10824942/Mur_LT1-bugfix.pptx)

**Comment by jason-milbrandt** [comment]
Melissa fixed the bug and tested it.  Merged back to master; now: v5.2.2.
