### ISSUE TITLE
Improvement to the calculation of diam_ice 

### ISSUE THREAD

**Issue by MelissaCholette** [jason-milbrandt/P3-microphysics#21]
Branch name: mods-diamice. Instead of using an assumed density of 500 kgm-3, just takes the value in the lookup table to get diam_ice. This is important for ice category destination with multi-cat and other processes, such as freezing. The modifications have been done in v5.2.4: ready to be merge to the master.

**Comment by jason-milbrandt** [comment]
Merged to MASTER branch; added tag 'v5.2.4'.

Deleted branch 'mod-diamice'.

**Comment by MelissaCholette** [comment]
It looks like the 1D results are very sensitive to the choice on how to compute the diameter for merging and freezing processes. This will affect only nCat>1. Attached is some results describing the issue.

**Comment by MelissaCholette** [comment]
[Impacts of new LT1.pptx](https://github.com/jason-milbrandt/P3-microphysics/files/11558847/Impacts.of.new.LT1.pptx)
It is also including some differences in precipitation type w.r.t the new lookup table 1, which increases the ice-rain collection.
