### ISSUE TITLE
Port recent bug fixes from v5.1 to v4 (to complete v4, pre-testing for WRF)

### ISSUE THREAD

**Issue by jason-milbrandt** [jason-milbrandt/P3-microphysics#4]

**Comment by MelissaCholette** [comment]
Did it (see branch dev-v4changes).

**Comment by jason-milbrandt** [comment]
- Made one correction to Melissa's mods.
- Changed branch name from 'dev-v4changes' to 'bugfix-from5.2' (to conform to P3-workflow protocol, to be announced soon)
- Merged to MASTER --> now, v4.5.1
